receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318

processors:
  batch: 
    timeout: 1s
  memory_limiter:
    limit_mib: 4096
    check_interval: 5s
    spike_limit_mib: 512
  resourcedetection:
    detectors: ["system"]

extensions:
  health_check:
    endpoint: 0.0.0.0:13133
  pprof:
    endpoint: 0.0.0.0:1777
  zpages:
    endpoint: 0.0.0.0:55679

exporters:
  otlp:
    endpoint: 0.0.0.0:14317
    tls:
      insecure: true
  file/default:
    path: ./logs/default.json
    append: false
  file/dito:
    path: ./logs/dito.json
    append: false

connectors:
  dito:
    non_error_sampling_fraction: 2

service:
  extensions: [health_check, pprof, zpages]
  pipelines:
    traces/default:
      receivers: [otlp]
      processors: [memory_limiter, resourcedetection, batch]
      exporters: [file/default, dito, otlp]
    traces/dito:
      receivers: [dito]
      processors: [memory_limiter, batch]
      exporters: [file/dito, otlp]
    metrics/dito:
      receivers: [dito]
      processors: [memory_limiter, batch]
      exporters: [file/dito, otlp]