// <auto-generated />
using External.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace External.Data.Migrations
{
    [DbContext(typeof(ExternalContext))]
    [Migration("20250224130456_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.2");

            modelBuilder.Entity("External.Data.Entities.ExternalUser", b =>
                {
                    b.Property<string>("EmailAddress")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("CostCenterCode")
                        .HasMaxLength(4)
                        .HasColumnType("TEXT");

                    b.Property<string>("ExternalProperty")
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.HasKey("EmailAddress");

                    b.ToTable("ExternalUsers");
                });
#pragma warning restore 612, 618
        }
    }
}
