// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ValidationTracer.Data;

#nullable disable

namespace ValidationTracer.Data.Migrations
{
    [DbContext(typeof(ValidationTracerContext))]
    partial class ValidationTracerContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ValidationTracer.Data.Entities.CostCenter", b =>
                {
                    b.Property<string>("Code")
                        .HasMaxLength(4)
                        .HasColumnType("nvarchar(4)");

                    b.HasKey("Code");

                    b.ToTable("CostCenters");
                });

            modelBuilder.Entity("ValidationTracer.Data.Entities.User", b =>
                {
                    b.Property<string>("EmailAddress")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("CostCenterCode")
                        .HasMaxLength(4)
                        .HasColumnType("nvarchar(4)");

                    b.Property<string>("ExternalApiProperty")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("ExternalDbProperty")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("InternalProperty")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.HasKey("EmailAddress");

                    b.HasIndex("CostCenterCode");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("ValidationTracer.Data.Entities.User", b =>
                {
                    b.HasOne("ValidationTracer.Data.Entities.CostCenter", "CostCenter")
                        .WithMany()
                        .HasForeignKey("CostCenterCode");

                    b.Navigation("CostCenter");
                });
#pragma warning restore 612, 618
        }
    }
}
