receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
  hostmetrics:
    collection_interval: 5m
    scrapers:
      cpu:
      disk:
      load:
      filesystem:
      memory:
      network:
      system:

processors:
  batch: 
    timeout: 1s
  memory_limiter:
    limit_mib: 4096
    check_interval: 5s
    spike_limit_mib: 512
  resourcedetection:
    detectors: ["system"]
  # filter out 401 status requests from traces and logs
  filter:
    error_mode: ignore
    traces:
      span:
        - 'attributes["http.response.status_code"] == 401'
      spanevent:
        - 'attributes["http.response.status_code"] == 401'
    logs:
      log_record:
        - 'attributes["http.response.status_code"] == 401'

exporters:
  otlp:
    endpoint: localhost:14317
    tls:
      insecure: true

connectors:
  dito:

service:
  pipelines:
    traces/default:
      receivers: [otlp]
      processors: [memory_limiter, filter, batch, resourcedetection]
      exporters: [dito, otlp]
    traces/dito:
      receivers: [dito]
      processors: [memory_limiter, batch]
      exporters: [otlp]
    metrics/dito:
      receivers: [dito]
      processors: [memory_limiter, batch]
      exporters: [otlp]
    metrics/default:
      receivers: [otlp, hostmetrics]
      processors: [memory_limiter, batch, resourcedetection]
      exporters: [otlp]
    logs/default:
      receivers: [otlp]
      processors: [memory_limiter, filter, batch, resourcedetection]
      exporters: [otlp]