receivers:
  otlp:
    protocols:
      http:
        endpoint: 0.0.0.0:4318
      grpc:
        endpoint: 0.0.0.0:4317
  hostmetrics:
    collection_interval: 5m
    scrapers:
      cpu:
      disk:
      load:
      filesystem:
      memory:
      network:
      system:

processors:
  batch:
    timeout: 1s
  memory_limiter:
    limit_mib: 4096
    check_interval: 5s
    spike_limit_mib: 512
  resourcedetection:
    detectors: ["system"]
  # filter out 401 status requests from traces and logs
  filter:
    error_mode: ignore
    traces:
      span:
        - 'attributes["http.response.status_code"] == 401'
      spanevent:
        - 'attributes["http.response.status_code"] == 401'
    logs:
      log_record:
        - 'attributes["http.response.status_code"] == 401'

exporters:
  otlp/grafana:
    endpoint: "lgtm:4317"
    tls:
      insecure: true

connectors:
  dito:

extensions:
  health_check:
    endpoint: 0.0.0.0:13133
  pprof:
    endpoint: 0.0.0.0:1777
  zpages:
    endpoint: 0.0.0.0:55679

service:
  extensions: [health_check, pprof, zpages]
  pipelines:
    traces/default:
      receivers: [otlp]
      processors: [memory_limiter, filter, batch]
      exporters: [dito, otlp/grafana]
    traces/dito:
      receivers: [dito]
      processors: [memory_limiter, batch, resourcedetection]
      exporters: [otlp/grafana]
    metrics/dito:
      receivers: [dito]
      processors: [memory_limiter, batch, resourcedetection]
      exporters: [otlp/grafana]
    metrics/default:
      receivers: [otlp, hostmetrics]
      processors: [memory_limiter, batch]
      exporters: [otlp/grafana]
    logs/default:
      receivers: [otlp]
      processors: [memory_limiter, filter, batch]
      exporters: [otlp/grafana]
