receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318
  hostmetrics:
    collection_interval: 60s
    scrapers:
      cpu:
      load:
      memory:
      disk:
      filesystem:
      network:

processors:
  batch: 
    timeout: 1s
  memory_limiter:
    limit_mib: 8192
    check_interval: 5s
    spike_limit_mib: 512
  resourcedetection:
    detectors: ["system"]
  groupbytrace:

extensions:
  health_check:
    endpoint: 0.0.0.0:13133
  pprof:
    endpoint: 0.0.0.0:1777
  zpages:
    endpoint: 0.0.0.0:55679

exporters:
  otlp:
    endpoint: 0.0.0.0:14317
    tls:
      insecure: true

connectors:
  dito:

service:
  extensions: [health_check, pprof, zpages]
  pipelines:
    traces/default:
      receivers: [otlp]
      processors: [memory_limiter, resourcedetection, batch, groupbytrace]
      exporters: [dito, otlp]
    traces/dito:
      receivers: [dito]
      processors: [memory_limiter, batch]
      exporters: [otlp]
    metrics/dito:
      receivers: [dito]
      processors: [memory_limiter, batch]
      exporters: [otlp]
    metrics/default:
      receivers: [otlp, hostmetrics]
      processors: [memory_limiter, batch]
      exporters: [otlp]
    logs/default:
      receivers: [otlp]
      processors: [memory_limiter, batch]
      exporters: [otlp]