receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318
processors:
  batch:
# filter out
# ScopeSpans SchemaURL: 
# InstrumentationScope OpenTelemetry.Instrumentation.SqlClient 1.7.0.1173
  filter:
    error_mode: ignore
    traces:
      span:
        - 'scope.name == "OpenTelemetry.Instrumentation.SqlClient"'

exporters:
  debug:
    verbosity: detailed
  file:
    path: ./logs/otelcol.json
    append: false
  otlp:
    endpoint: http://localhost:19218
    tls:
      insecure: true
    headers:
      x-otlp-api-key: 67ece10f8749566cbf983b1c346ee640
  azuremonitor:
    connection_string: "InstrumentationKey=61b2b33b-ed9b-4519-9e49-3830f5976c32;IngestionEndpoint=https://westeurope-5.in.applicationinsights.azure.com/;LiveEndpoint=https://westeurope.livediagnostics.monitor.azure.com/;ApplicationId=d30bd882-7ff0-4006-b400-4bd8c93797a1"

service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch, filter]
      exporters: [debug, otlp, file, azuremonitor]
    metrics:
      receivers: [otlp]
      processors: [batch]
      exporters: [otlp, azuremonitor]
    logs:
      receivers: [otlp]
      processors: [batch]
      exporters: [otlp, azuremonitor]