receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318

processors:
  batch:
    timeout: 1s
  memory_limiter:
    limit_mib: 4096
    check_interval: 5s
    spike_limit_mib: 512
  resourcedetection:
    detectors: ["system"]

exporters:
  debug:

connectors:
  dito:

services:
  pipelines:
    traces/default:
      receivers: [otlp]
      processors: [memory_limiter, filter, batch]
      exporters: [dito, debug]
    traces/dito:
      receivers: [dito]
      processors: [memory_limiter, batch, resourcedetection]
      exporters: [debug]
    metrics/dito:
      receivers: [dito]
      processors: [memory_limiter, batch, resourcedetection]
      exporters: [debug]
    metrics/default:
      receivers: [otlp, hostmetrics]
      processors: [memory_limiter, batch]
      exporters: [debug]
    logs/default:
      receivers: [otlp]
      processors: [memory_limiter, filter, batch]
      exporters: [debug]
